name: CI/CD for MERN App with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔐 Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.12201285}}
        password: ${{ secrets.Nafeez@123}}

    - name: 📦 Build & Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest

    - name: 📦 Build & Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./notes-app-backend
        file: ./notes-app-backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
